development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Mongoid can connect to a URI accepted by the driver:
      uri: "<%= ENV['MONGODB_URI'] %>"
      options:
        server_selection_timeout: 5

  # Configure Mongoid specific options. (optional)
  options:
    # Application name that is printed to the mongodb logs upon establishing
    # a connection in server versions >= 3.4. Note that the name cannot
    # exceed 128 bytes. It is also used as the database name if the
    # database name is not explicitly defined. (default: nil)
    app_name: WebHooks-DEV

    # Create indexes in background by default. (default: false)
    # background_indexing: false

    # Mark belongs_to associations as required by default, so that saving a
    # model with a missing belongs_to association will trigger a validation
    # error. (default: true)
    # belongs_to_required_by_default: true

    # Raise an exception when a field is redefined. (default: false)
    # duplicate_fields_exception: false

    # Include the root model name in json serialization. (default: false)
    # include_root_in_json: false

    # Include the _type field in serialization. (default: false)
    include_type_for_serialization: true

    # Whether to join nested persistence contexts for atomic operations
    # to parent contexts by default. (default: false)
    # join_contexts: false

    # Set the Mongoid and Ruby driver log levels when Mongoid is not using
    # Ruby on Rails logger instance. (default: :info)
    log_level: :debug

    # Preload all models in development, needed when models use
    # inheritance. (default: false)
    # preload_models: false

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    raise_not_found_error: false

    # Raise an error when defining a scope with the same name as an
    # existing method. (default: false)
    # scope_overwrite_exception: false

    # Use ActiveSupport's time zone in time operations instead of
    # the Ruby default time zone. See the time zone section below for
    # further information. (default: true)
    # use_activesupport_time_zone: true

    # Return stored times as UTC. See the time zone section below for
    # further information. Most applications should not use this option.
    # (default: false)
    # use_utc: false

test:
  clients:
    default:
      uri: "<%= ENV['MONGODB_URI'].gsub /development/, 'test' %>"
      options:
        server_selection_timeout: 5
  options:
    app_name: WebHooks-TEST
    include_type_for_serialization: true
    log_level: :debug
    raise_not_found_error: false

production:
  clients:
    default:
      uri: "<%= ENV['MONGODB_URI'] %>"
      options:
        server_selection_timeout: 5
  options:
    app_name: WebHooks-PROD
    include_type_for_serialization: true
    log_level: :error
    raise_not_found_error: false